# Generated by Django 3.0.3 on 2020-05-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20200425_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
