# Generated by Django 3.0.3 on 2020-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20200503_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
