# Generated by Django 3.0.5 on 2020-04-19 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20200419_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(default='SALARY', max_length=20),
        ),
    ]
