# Generated by Django 3.0.5 on 2020-05-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20200503_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='date',
            new_name='income_date',
        ),
    ]
